# Generated by Django 5.1.4 on 2026-09-02 20:49

import apps.site_settings.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSnapshot',
            fields=[
                ('id', models.CharField(default=apps.site_settings.models.generate_backup_id, max_length=64, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('backup_type', models.CharField(default='manual', max_length=32)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('data_payload', models.JSONField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('created_by', models.CharField(default='system', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettingsAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.CharField(default='admin@veloce.co.ke', max_length=255)),
                ('section', models.CharField(max_length=64)),
                ('action', models.CharField(default='update', max_length=64)),
                ('old_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('changes_diff', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.JSONField(default=apps.site_settings.models.default_general_settings)),
                ('appearance', models.JSONField(default=apps.site_settings.models.default_appearance_settings)),
                ('tax', models.JSONField(default=apps.site_settings.models.default_tax_settings)),
                ('receipts', models.JSONField(default=apps.site_settings.models.default_receipts_settings)),
                ('backup', models.JSONField(default=apps.site_settings.models.default_backup_settings)),
                ('payments', models.JSONField(default=apps.site_settings.models.default_payments_settings)),
                ('notifications', models.JSONField(default=apps.site_settings.models.default_notifications_settings)),
                ('seo', models.JSONField(default=apps.site_settings.models.default_seo_settings)),
                ('access_control', models.JSONField(default=apps.site_settings.models.default_access_control_settings)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.CharField(default=apps.site_settings.models.generate_theme_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('primary_color', models.CharField(default='#4f46e5', max_length=32)),
                ('secondary_color', models.CharField(default='#06b6d4', max_length=32)),
                ('accent_color', models.CharField(default='#f59e0b', max_length=32)),
                ('background_color', models.CharField(default='#0f172a', max_length=32)),
                ('surface_color', models.CharField(default='#1e293b', max_length=32)),
                ('text_color', models.CharField(default='#f8fafc', max_length=32)),
                ('is_active', models.BooleanField(default=False)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_system_preset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
