# Generated by Django 5.1.4 on 2026-09-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsauditlog',
            name='user_email',
            field=models.CharField(default='admin@ropenix.co.ke', max_length=255),
        ),
    ]
