# Generated by Django 5.1.4 on 2026-09-07 19:19

import apps.suppliers.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_inventoryauditlog_products_in_product_80f720_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default=apps.suppliers.models.generate_supplier_code, max_length=64, unique=True)),
                ('name', models.CharField(help_text='Supplier or Artisan Name / Contact Person', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', help_text='Business / Legal Entity Name', max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('physical_address', models.TextField(blank=True, default='')),
                ('tax_pin', models.CharField(blank=True, default='', help_text='KRA PIN / VAT ID', max_length=50)),
                ('payment_terms', models.CharField(choices=[('Consignment Sale', 'Consignment Sale (Pay on Sale)'), ('Immediate', 'Immediate / Cash on Delivery'), ('Net 15', 'Net 15 Days'), ('Net 30', 'Net 30 Days'), ('Bi-weekly', 'Bi-weekly Settlement'), ('Monthly', 'Monthly Settlement')], default='Consignment Sale', max_length=50)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=100)),
                ('mpesa_number', models.CharField(blank=True, default='', help_text='M-PESA Paybill / Till or Phone', max_length=50)),
                ('mpesa_account_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], db_index=True, default='Active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'name'], name='suppliers_s_status_3f308a_idx'), models.Index(fields=['code'], name='suppliers_s_code_d1984e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierIntakeBatch',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, default=apps.suppliers.models.generate_grn_code, max_length=64, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, default='', max_length=64)),
                ('quantity_received', models.IntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_note_ref', models.CharField(blank=True, default='', help_text='Supplier Delivery Note #', max_length=100)),
                ('invoice_ref', models.CharField(blank=True, default='', help_text='Supplier Invoice #', max_length=100)),
                ('status', models.CharField(choices=[('Received', 'Goods Received & Stocked'), ('Inspected', 'Quality Verified & Passed'), ('Returned', 'Partial / Full Return to Supplier'), ('Cancelled', 'Cancelled Batch')], default='Received', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('received_by', models.CharField(default='Warehouse Manager', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_batches', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_batches', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Intake Batch',
                'verbose_name_plural': 'Supplier Intake Batches',
                'ordering': ['-received_date'],
                'indexes': [models.Index(fields=['supplier', '-received_date'], name='suppliers_s_supplie_b1f415_idx'), models.Index(fields=['batch_number'], name='suppliers_s_batch_n_5dc581_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierLedgerEntry',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('STOCK_INTAKE', 'Stock Intake (GRN)'), ('SALE_PAYABLE', 'Product Sale (Payable Accrued)'), ('PAYMENT_DISBURSED', 'Supplier Payout (Balance Cleared)'), ('RETURN_DEBIT', 'Customer Return / Stock Return'), ('ADJUSTMENT', 'Manual Balance Adjustment')], max_length=30)),
                ('reference_id', models.CharField(db_index=True, help_text='Order ID, GRN ID, or SPAY ID', max_length=64)),
                ('description', models.TextField()),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount reducing debt (e.g. Payments)', max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount increasing debt (e.g. Sales owed)', max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Ledger Entry',
                'verbose_name_plural': 'Supplier Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supplier', '-created_at'], name='suppliers_s_supplie_e6cb33_idx'), models.Index(fields=['reference_id'], name='suppliers_s_referen_31a85c_idx'), models.Index(fields=['entry_type'], name='suppliers_s_entry_t_5139fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(db_index=True, default=apps.suppliers.models.generate_payment_ref, max_length=64, unique=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount disbursed in KSh', max_digits=12)),
                ('payment_method', models.CharField(choices=[('M-PESA', 'M-PESA Paybill / Till / Direct'), ('Bank Transfer', 'EFT / RTGS / Bank Wire'), ('Cheque', 'Corporate Bank Cheque'), ('Cash', 'Petty Cash Voucher'), ('Card', 'Debit / Credit Card')], default='M-PESA', max_length=50)),
                ('transaction_code', models.CharField(blank=True, default='', help_text='M-PESA confirmation or Bank Ref code', max_length=100)),
                ('settlement_period_start', models.DateField(blank=True, null=True)),
                ('settlement_period_end', models.DateField(blank=True, null=True)),
                ('allocated_batches_or_orders', models.JSONField(blank=True, default=list, help_text='List of Order/GRN IDs settled')),
                ('status', models.CharField(choices=[('Completed', 'Disbursed & Confirmed'), ('Pending', 'Pending Authorization'), ('Void', 'Void / Cancelled')], default='Completed', max_length=20)),
                ('receipt_attachment_url', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('processed_by', models.CharField(default='Finance Admin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Payment',
                'verbose_name_plural': 'Supplier Payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['supplier', '-payment_date'], name='suppliers_s_supplie_f054fb_idx'), models.Index(fields=['payment_reference'], name='suppliers_s_payment_824ce8_idx'), models.Index(fields=['transaction_code'], name='suppliers_s_transac_0dbd95_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('supplier_sku', models.CharField(blank=True, default='', max_length=64)),
                ('agreed_cost_price', models.DecimalField(decimal_places=2, help_text='Agreed cost per unit payable to supplier in KSh', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Retail selling price in KSh', max_digits=12)),
                ('quantity_received', models.IntegerField(default=0, help_text='Cumulative units received from this supplier')),
                ('quantity_sold', models.IntegerField(default=0, help_text='Cumulative units sold from this supplier')),
                ('lead_time_days', models.IntegerField(default=3)),
                ('is_primary_supplier', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Product Link',
                'verbose_name_plural': 'Supplier Product Links',
                'indexes': [models.Index(fields=['supplier', 'product'], name='suppliers_s_supplie_ae870f_idx')],
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
