# Generated by Django 5.1.4 on 2026-08-29 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPointsLedger',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Points Earned'), ('redeem', 'Points Redeemed'), ('bonus', 'Promotional Bonus'), ('adjustment', 'Admin Adjustment')], default='earn', max_length=20)),
                ('points_amount', models.IntegerField(help_text='Positive for earned, negative for redeemed')),
                ('description', models.CharField(max_length=255)),
                ('order_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyalty Points Ledger Entry',
                'verbose_name_plural': 'Loyalty Points Ledger Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('order', 'Order Status Alert'), ('affiliate', 'Affiliate Commission'), ('support', 'Support Ticket Update'), ('system', 'System Announcement')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link_url', models.URLField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('partner_tier', models.CharField(default='Standard Member', max_length=50)),
                ('loyalty_points', models.IntegerField(default=150)),
                ('commission_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_affiliate', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=1024)),
                ('bio', models.TextField(blank=True, default='')),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='Nairobi', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='00100', max_length=20)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
