# Generated by Django 5.1.4 on 2026-08-31 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionalEmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('order.placed.customer', 'Order Placed (Customer Confirmation)'), ('order.placed.admin', 'Order Placed (Admin Alert)'), ('order.shipped.customer', 'Order Shipped (Customer Notice)'), ('order.delivered.customer', 'Order Delivered (Customer Notice)'), ('order.cancelled.customer', 'Order Cancelled (Customer Notice)'), ('payment.failed.customer', 'Payment Failed (Customer Alert)'), ('contact.submitted.admin', 'Contact Inquiry (Admin Notification)'), ('contact.submitted.customer', 'Contact Acknowledgment (Customer Auto-Reply)'), ('user.welcome.customer', 'User Welcome (Customer Onboarding)'), ('user.password_reset.customer', 'Password Reset (Customer)'), ('marketing.abandoned_cart.customer', 'Abandoned Cart Reminder')], db_index=True, max_length=64)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('sender', models.CharField(blank=True, default='', max_length=255)),
                ('reply_to', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent Successfully'), ('failed', 'Delivery Failed'), ('skipped', 'Skipped / Suppressed')], db_index=True, default='queued', max_length=20)),
                ('error_detail', models.TextField(blank=True, default='', help_text='Detailed error traceback or failure rationale')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Context payload used for rendering')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transactional Email Log',
                'verbose_name_plural': 'Transactional Email Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='emails_tran_event_t_610959_idx'), models.Index(fields=['recipient', '-created_at'], name='emails_tran_recipie_41d50a_idx'), models.Index(fields=['status', '-created_at'], name='emails_tran_status_da19db_idx')],
            },
        ),
    ]
