# Generated by Django 5.1.4 on 2026-08-29 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Pending-Cancellation', 'Pending Cancellation')], db_index=True, default='Pending', max_length=30)),
                ('affiliate_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('payment_method', models.CharField(default='M-PESA', max_length=50)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('shipping_address', models.TextField(blank=True, default='')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, default='', max_length=64)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selected_variations', models.JSONField(blank=True, default=dict, help_text="Chosen variations e.g. {'Size': 'M'}")),
                ('digital_download_key', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('order_id_ref', models.CharField(db_index=True, help_text='Original order reference string', max_length=64)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('return_reason', models.TextField(help_text='Reason provided by customer')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved for Return'), ('rejected', 'Request Rejected'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('customer_notes', models.TextField(blank=True, default='')),
                ('user_notes', models.TextField(blank=True, default='')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('evidence_images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='orders.order')),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnStatusHistoryEntry',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('changed_by', models.CharField(default='System Admin', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.returnrequest')),
            ],
            options={
                'verbose_name': 'Return Status History Entry',
                'verbose_name_plural': 'Return Status History Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
