# Generated by Django 5.1.4 on 2026-08-29 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('affiliate_code', models.CharField(db_index=True, max_length=32)),
                ('campaign_slug', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.URLField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Affiliate Click Log',
                'verbose_name_plural': 'Affiliate Click Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('affiliate_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('partner_tier', models.CharField(choices=[('Silver', 'Silver (10%)'), ('Gold', 'Gold (12%)'), ('Platinum', 'Platinum (15%)')], default='Silver', max_length=20)),
                ('payment_method', models.CharField(default='M-Pesa B2C', max_length=50)),
                ('mpesa_number', models.CharField(blank=True, default='', max_length=30)),
                ('bank_details', models.JSONField(blank=True, default=dict)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('clicks_count', models.IntegerField(default=0)),
                ('conversions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateCampaign',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('target_url', models.URLField(default='https://veloce.co.ke/', max_length=1024)),
                ('custom_slug', models.SlugField(max_length=100, unique=True)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='affiliates.affiliateprofile')),
            ],
            options={
                'verbose_name': 'Affiliate Campaign',
                'verbose_name_plural': 'Affiliate Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('affiliate_code', models.CharField(db_index=True, max_length=32)),
                ('order_id', models.CharField(db_index=True, max_length=64)),
                ('product_name', models.CharField(default='Veloce Store Item', max_length=255)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate_snapshot', models.CharField(default='10%', max_length=50)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Hold'), ('approved', 'Approved'), ('paid', 'Paid Out'), ('voided', 'Voided')], db_index=True, default='pending', max_length=20)),
                ('pending_until', models.DateTimeField(blank=True, null=True)),
                ('voided_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliates.affiliateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='M-Pesa B2C', max_length=50)),
                ('reference_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('processed', 'Successfully Processed'), ('pending', 'Pending Transfer'), ('failed', 'Transfer Failed')], default='processed', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='affiliates.affiliateprofile')),
            ],
            options={
                'verbose_name': 'Payout Record',
                'verbose_name_plural': 'Payout Records',
                'ordering': ['-processed_at'],
            },
        ),
    ]
