# Generated by Django 5.1.4 on 2026-08-31 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliateprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Affiliate Profile', 'verbose_name_plural': 'Affiliate Profiles'},
        ),
        migrations.AlterModelOptions(
            name='commissionentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commission Entry', 'verbose_name_plural': 'Commission Entries'},
        ),
        migrations.AddIndex(
            model_name='affiliateprofile',
            index=models.Index(fields=['user', 'status'], name='affiliates__user_id_a8015c_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateprofile',
            index=models.Index(fields=['affiliate_code', 'status'], name='affiliates__affilia_21e01f_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionentry',
            index=models.Index(fields=['affiliate', 'status', '-created_at'], name='affiliates__affilia_9e3e54_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionentry',
            index=models.Index(fields=['affiliate_code', '-created_at'], name='affiliates__affilia_0b537a_idx'),
        ),
    ]
