# Generated by Django on 2026-08-15
import uuid
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content', models.TextField(help_text='Full markdown or HTML article body')),
                ('author', models.CharField(default='Veloce Editorial Team', max_length=100)),
                ('category', models.CharField(default='E-commerce Guides', max_length=100)),
                ('featured_image', models.URLField(blank=True, default='', max_length=1024)),
                ('read_time', models.CharField(default='4 min read', max_length=30)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Large, compelling primary headline', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='', help_text='Supporting sub-headline or description')),
                ('description', models.TextField(blank=True, default='', help_text='Detailed supporting paragraph')),
                ('badge_text', models.CharField(blank=True, default='', help_text='Optional eyebrow tag or promo badge', max_length=100)),
                ('primary_button_text', models.CharField(default='Shop Collection', help_text='Primary CTA button text', max_length=100)),
                ('primary_button_url', models.CharField(default='/products', help_text='Primary CTA destination link or tab', max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, default='', help_text='Optional secondary CTA button text', max_length=100)),
                ('secondary_button_url', models.CharField(blank=True, default='', help_text='Optional secondary CTA destination link', max_length=255)),
                ('hero_image', models.ImageField(blank=True, help_text='Marketing or product cutout image', null=True, upload_to='hero_banners/')),
                ('hero_image_url', models.URLField(blank=True, default='', help_text='Fallback direct image URL', max_length=1024)),
                ('background_type', models.CharField(choices=[('color', 'Solid Color'), ('image', 'Background Image')], default='color', help_text='Solid color or background image', max_length=20)),
                ('background_color', models.CharField(default='#0f172a', help_text='Solid background color (hex, e.g. #0f172a)', max_length=50)),
                ('background_image', models.ImageField(blank=True, help_text='Full background scenery image', null=True, upload_to='hero_backgrounds/')),
                ('background_image_url', models.URLField(blank=True, default='', help_text='Fallback direct background image URL', max_length=1024)),
                ('background_position', models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', help_text='Background image alignment', max_length=50)),
                ('overlay_enabled', models.BooleanField(default=True, help_text='Enable dark/tint overlay on background image')),
                ('overlay_color', models.CharField(default='#000000', help_text='Overlay color (hex, e.g. #000000)', max_length=50)),
                ('overlay_opacity', models.FloatField(default=0.5, help_text='Overlay opacity between 0.0 (transparent) and 1.0 (fully opaque)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('text_color', models.CharField(default='#ffffff', help_text='Primary text color (hex, e.g. #ffffff)', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this banner is visible on the storefront')),
                ('display_order', models.IntegerField(db_index=True, default=0, help_text='Display priority order (lowest number appears first)')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional publish schedule start datetime', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional publish schedule expiry datetime', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('target_segment', models.CharField(default='All Active Customers', max_length=100)),
                ('template_type', models.CharField(default='newsletter', max_length=50)),
                ('body_content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('recipient_count', models.IntegerField(default=0)),
                ('open_rate', models.FloatField(default=0.0)),
                ('click_rate', models.FloatField(default=0.0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Campaign',
                'verbose_name_plural': 'Email Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomServiceRequest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('service_type', models.CharField(default='Branded Uniform Printing', max_length=100)),
                ('requirements', models.TextField()),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12)),
                ('status', models.CharField(choices=[('new', 'New Request'), ('in_review', 'Under Review'), ('contacted', 'Client Contacted'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Service Request',
                'verbose_name_plural': 'Custom Service Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(default='Orders & Shipping', max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('support_agent', 'Support Agent'), ('system', 'Automated Bot')], default='customer', max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='content.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
