# Generated by Django 5.1.4 on 2026-09-01 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_inventoryauditlog_products_in_product_80f720_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_id', models.CharField(db_index=True, max_length=120)),
                ('reservation_token', models.CharField(db_index=True, max_length=120, unique=True)),
                ('items_payload', models.JSONField(default=list, help_text='Snapshot of reserved SKU items and quantities')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Hold'), ('COMMITTED', 'Committed to Order'), ('EXPIRED', 'Expired / Released'), ('CANCELLED', 'Cancelled by User')], db_index=True, default='ACTIVE', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['cart_id', 'status'], name='inventory_i_cart_id_5f8328_idx'), models.Index(fields=['expires_at', 'status'], name='inventory_i_expires_3e2f43_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Total physical stock in warehouse')),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Stock currently on hold during active checkouts')),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('allow_backorders', models.BooleanField(default=False)),
                ('warehouse_location', models.CharField(blank=True, default='Main Nairobi Hub', max_length=120)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_record', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'indexes': [models.Index(fields=['sku'], name='inventory_i_sku_78cea7_idx'), models.Index(fields=['stock_quantity'], name='inventory_i_stock_q_d3a54a_idx')],
            },
        ),
    ]
