# Generated by Django 5.1.4 on 2026-08-29 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Product Display Name', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', help_text='URL-friendly slug', max_length=280)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed product description')),
                ('category', models.CharField(db_index=True, default='General', max_length=100)),
                ('type', models.CharField(choices=[('physical', 'Physical Product'), ('digital', 'Digital Asset / Download'), ('service', 'Service / Custom Order')], default='physical', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Draft', 'Draft'), ('Archived', 'Archived')], db_index=True, default='Active', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current selling price in KSh', max_digits=12)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='MSRP or strikethrough price', max_digits=12, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price for profit calculation', max_digits=12, null=True)),
                ('stock', models.IntegerField(default=10, help_text='Current available inventory quantity')),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Threshold to flag low stock warning')),
                ('track_stock', models.BooleanField(default=True, help_text='Enforce inventory tracking on orders')),
                ('rating', models.FloatField(default=5.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('variations', models.JSONField(blank=True, default=list, help_text='List of variant options (e.g., Color, Size)')),
                ('digital_file_url', models.URLField(blank=True, default='', help_text='Secure digital file payload link', max_length=1024)),
                ('download_limit', models.IntegerField(default=5, help_text='Max downloads permitted per purchase')),
                ('image_url', models.URLField(blank=True, default='', help_text='Primary product thumbnail URL', max_length=1024)),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of additional image URLs')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight product in storefront listings')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated search tags', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible JSON key-value store for extra attributes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomClothingDesign',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('item_type', models.CharField(default='tshirt', max_length=50)),
                ('fabric_color', models.CharField(default='Navy Blue', max_length=50)),
                ('custom_text', models.CharField(blank=True, default='', max_length=255)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=50)),
                ('print_position', models.CharField(default='Chest Center', max_length=50)),
                ('logo_image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('quantity', models.IntegerField(default=1)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=1800.0, max_digits=12)),
                ('status', models.CharField(choices=[('quote_requested', 'Quote Requested'), ('approved', 'Approved'), ('in_production', 'In Production'), ('shipped', 'Shipped')], default='quote_requested', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Clothing Design',
                'verbose_name_plural': 'Custom Clothing Designs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('product_sku', models.CharField(db_index=True, max_length=64)),
                ('product_name', models.CharField(max_length=255)),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('stock_change', models.IntegerField()),
                ('reason', models.CharField(choices=[('manual-update', 'Manual Adjustment'), ('order-placement', 'Order Sales Deduction'), ('restock', 'Inbound Restock'), ('system-init', 'System Initialization')], db_index=True, default='manual-update', max_length=30)),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.CharField(help_text='Human formatted timestamp', max_length=64)),
                ('created_by', models.CharField(default='Admin Staff', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='products.product')),
            ],
            options={
                'verbose_name': 'Inventory Audit Log',
                'verbose_name_plural': 'Inventory Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Approval'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
