# Generated by Django 5.1.4 on 2026-08-29 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='previous_slugs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
