# Generated by Django 5.1.4 on 2026-08-29 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HappyHourWindow',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.CharField(default='14:00', help_text='Format HH:MM', max_length=10)),
                ('end_time', models.CharField(default='16:00', help_text='Format HH:MM', max_length=10)),
                ('days_of_week', models.JSONField(default=list, help_text='List of active weekday integers 0=Sun .. 6=Sat')),
                ('discount_percentage', models.IntegerField(default=50, help_text='Percentage discount e.g. 50')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Happy Hour Window',
                'verbose_name_plural': 'Happy Hour Windows',
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Zone Name, e.g. Nairobi CBD', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('min_distance_km', models.FloatField(default=0.0)),
                ('max_distance_km', models.FloatField(default=10.0)),
                ('base_fee', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('regions', models.JSONField(blank=True, default=list, help_text='List of covered sub-regions or towns')),
                ('estimated_delivery_time', models.CharField(default='30-45 mins', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_distance_km'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('tax_name', models.CharField(default='VAT', max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, default=16.0, help_text='Default 16.00 for Kenya VAT', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('flat_rate', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('estimated_days', models.IntegerField(default=1)),
                ('is_enabled', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['flat_rate'],
            },
        ),
    ]
