# Generated by Django 5.1.4 on 2026-09-01 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, default='', help_text='City, Region, or Delivery Location', max_length=255),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['location'], name='customers_c_locatio_b2f73c_idx'),
        ),
    ]
