# Generated by Django 5.1.4 on 2026-09-01 23:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=120)),
                ('reservation_token', models.CharField(blank=True, db_index=True, max_length=120)),
                ('provider', models.CharField(choices=[('MPESA', 'Safaricom M-Pesa Daraja'), ('STRIPE', 'Stripe Card Payment'), ('PAYSTACK', 'Paystack Multi-Currency'), ('COD', 'Cash on Delivery')], db_index=True, default='MPESA', max_length=20)),
                ('provider_reference', models.CharField(db_index=True, help_text='CheckoutRequestID or Stripe PaymentIntent ID', max_length=200, unique=True)),
                ('receipt_number', models.CharField(blank=True, db_index=True, help_text='e.g. M-Pesa Receipt Code (QAB123456)', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Initiation'), ('PROCESSING', 'Processing Gateway Callback'), ('COMPLETED', 'Completed & Verified'), ('FAILED', 'Failed / Insufficient Funds'), ('CANCELLED', 'Cancelled by Customer'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id', 'status'], name='payments_pa_order_i_ed562a_idx'), models.Index(fields=['provider', 'status'], name='payments_pa_provide_c3bda6_idx')],
            },
        ),
    ]
