# Generated by Django 5.1.4 on 2026-09-01 23:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_inventoryauditlog_products_in_product_80f720_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(help_text='ISO 2-letter code: KE, UG, TZ, RW', max_length=2, unique=True)),
                ('country_name', models.CharField(max_length=64)),
                ('currency_code', models.CharField(default='KES', help_text='Default currency e.g. KES, UGX, TZS, RWF', max_length=3)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='e.g. 16.00 for Kenya 16% VAT', max_digits=5)),
                ('tax_identifier_name', models.CharField(default='VAT', help_text='e.g. VAT, PIN / TIN', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Country Tax Rate',
                'verbose_name_plural': 'Country Tax Rates',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(db_index=True, default='KES', help_text='KES, UGX, TZS, RWF, USD', max_length=3)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_start_at', models.DateTimeField(blank=True, null=True)),
                ('sale_end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'currency', 'is_active'], name='pricing_pro_product_dd7ff4_idx')],
                'unique_together': {('product', 'currency')},
            },
        ),
    ]
