# Generated by Django 5.1.4 on 2026-09-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orders_orde_user_id_0ae59f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
